# This is a basic workflow to help you get started with Actions

name: CI to bitbucket

on: [push, delete]

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        ref: 'master'
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
         key: ${{ secrets.BITBUCKET_SSH_PRIVATE_KEY }}
         name: id_rsa # optional
         known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - run: |
        git remote add bitbucket git@bitbucket.org:Felipe_Navas/websocket-server-chat.git
        git config --global user.email "felipenavas.itec@gmail.com"
        git config --global user.name "Felipe Navas"
        git checkout master
        git push -f -u bitbucket master
